version: '3.8'

services:
    sveltekit:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "3030:3030"
        command: [ "node", "./build/index.js", "--host" ]
